version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - quotidian-ennui
      - aaron-mcgrath-adp
  - package_manager : "java:maven"
    directory: "/kie-rule-demo"
    update_schedule: "daily"
    default_reviewers:
     - quotidian-ennui
     - aaron-mcgrath-adp
